### ISSUE TITLE
'bool' object is not iterable

### ISSUE THREAD

**Issue by patparsch** [trifle/twitterresearch#14]

**Comment by trifle** [comment]
Hi @HuberSeppe,
I assume you found and fixed the root cause here. Would you mind briefly describing the issue? That's often helpful documentation for other users.
For the reference: You were getting `Boolean` items from helper functions out of `rest.py` - I guess what you hit was this line:
https://github.com/trifle/twitterresearch/blob/master/rest.py#L272
which yields a single `False` if there is an error.

**Comment by patparsch** [comment]
Hi trifle,

indeed this was my problem. Since it was not actually a issue with your script or program I thought I should not bother you.
Anyway, with functions that use two for loops within each other, I had the error mentioned in the title.
https://github.com/trifle/twitterresearch/blob/fd7a88e7333572f435bcdc6dcbba212ba067ea9f/examples.py#L118
Those would be for instance save_user_archive_to_file, save_user_archive_to_database.
I did not actually solve the problem. It just did not occur on my other computer for whatever reason.
So it seems the program tries iterating over page in this line: https://github.com/trifle/twitterresearch/blob/fd7a88e7333572f435bcdc6dcbba212ba067ea9f/examples.py#L126
And then gives me the error.
Happens with other helper functions as well, though.
