### ISSUE TITLE
Avoid incomplete tweets when querying Twitter's Streaming APIs

### ISSUE THREAD

**Issue by ajungherr** [trifle/twitterresearch#7]
Currently, when querying Twitter's Streaming APIs the process stops in direct reaction to its manual cancelation. This might be problematic as resulting .json files might end up with a final incomplete tweet thereby throwing subsequent analytical steps.

Here, it would be excellent to have a safeguard. For example by guaranteeing that the last tweet in any .json file is checked on completeness or by automatically deleting the last line of any .json file.

**Comment by trifle** [comment]
Thanks for the report.

Handling program exits and aborts needs to be done at the outermost level, that is in the script that's calling our libraries. The examples don't include a readymade solution since that's outside the scope of this project.

To help users handle this on their own, I've added an example in 113986b5c23b0abb498b7560246e4f25a1e6f762. This works by capturing the relevant Exceptions that are triggered by Ctrl-C (KeyboardInterrupt, SystemExit) and then properly closing the file.

Any program that uses *stream* capturing should use this strategy to make sure that tweets are fully written. The REST API isn't affected.
