### ISSUE TITLE
Persistent Error in the use of import.json()

### ISSUE THREAD

**Issue by ajungherr** [trifle/twitterresearch#8]
When using the function import.json() there appears a specific error repeatedly across various users. The function returns an error when trying to add data from json files to the database field "url". The error appears in the attempt to deduplicate the input and reads "NoneType" object has no attribute "lower".

As a quick fix, we simply stopped trying to fill the respective database field. Following this, the problem disappeared and the rest of the data loads perfectly. But as this hinders the analysis of hyperlinks in tweets it would be perfect if we would find a better solution.

**Comment by trifle** [comment]
Great find!
The order of processing steps in the function `deduplicate_lowercase` was wrong:
Instead of first eliminating empty values (None), the function directly tried to convert everything to lowercase. That doesn't work for None.

The order is now swapped in 6a2bfc9e0d68e9353760a104280afb7f2e8ddbdf which should fix the URL handling.
